// Mocks generated by Mockito 5.0.17 from annotations
// in ditonton/test/presentation/pages/tv/tv_show_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/tv/tv.dart' as _i10;
import 'package:ditonton/domain/entities/tv/tv_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/tv/get_tv_show_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/tv/get_tv_shows_recommendation.dart'
    as _i3;
import 'package:ditonton/domain/usecases/tv/get_watchlist_status_tv.dart'
    as _i6;
import 'package:ditonton/domain/usecases/tv/remove_watchlist_tv.dart' as _i5;
import 'package:ditonton/domain/usecases/tv/save_watchlist_tv.dart' as _i4;
import 'package:ditonton/presentation/provider/tv/tv_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTVShowDetail_0 extends _i1.Fake implements _i2.GetTVShowDetail {}

class _FakeGetTVShowsRecommendation_1 extends _i1.Fake
    implements _i3.GetTVShowsRecommendation {}

class _FakeSaveWatchlistTV_2 extends _i1.Fake implements _i4.SaveWatchlistTV {}

class _FakeRemoveWatchlistTV_3 extends _i1.Fake
    implements _i5.RemoveWatchlistTV {}

class _FakeGetWatchListStatusTV_4 extends _i1.Fake
    implements _i6.GetWatchListStatusTV {}

class _FakeTVDetail_5 extends _i1.Fake implements _i7.TVDetail {}

/// A class which mocks [TVDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVDetailNotifier extends _i1.Mock implements _i8.TVDetailNotifier {
  MockTVDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVShowDetail get getTVShowDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVShowDetail),
          returnValue: _FakeGetTVShowDetail_0()) as _i2.GetTVShowDetail);
  @override
  _i3.GetTVShowsRecommendation get getTVShowsRecommendation =>
      (super.noSuchMethod(Invocation.getter(#getTVShowsRecommendation),
              returnValue: _FakeGetTVShowsRecommendation_1())
          as _i3.GetTVShowsRecommendation);
  @override
  _i4.SaveWatchlistTV get saveWatchlistTV =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlistTV),
          returnValue: _FakeSaveWatchlistTV_2()) as _i4.SaveWatchlistTV);
  @override
  _i5.RemoveWatchlistTV get removeWatchlistTV =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlistTV),
          returnValue: _FakeRemoveWatchlistTV_3()) as _i5.RemoveWatchlistTV);
  @override
  _i6.GetWatchListStatusTV get getWatchListStatusTV => (super.noSuchMethod(
      Invocation.getter(#getWatchListStatusTV),
      returnValue: _FakeGetWatchListStatusTV_4()) as _i6.GetWatchListStatusTV);
  @override
  _i7.TVDetail get tvDetail => (super.noSuchMethod(Invocation.getter(#tvDetail),
      returnValue: _FakeTVDetail_5()) as _i7.TVDetail);
  @override
  _i9.RequestState get tvState =>
      (super.noSuchMethod(Invocation.getter(#tvState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  List<_i10.TV> get tvRecommendation =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendation),
          returnValue: <_i10.TV>[]) as List<_i10.TV>);
  @override
  _i9.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTVShowDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchTVShowDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlistTV(_i7.TVDetail? tv) => (super.noSuchMethod(
      Invocation.method(#addWatchlistTV, [tv]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlistTV(_i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlistTV, [tv]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
